; ------------------------------------------------------------------
; ORTAK AYARLAR
; ------------------------------------------------------------------
[env]
platform = espressif32
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200

monitor_filters = send_on_enter, colorize
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1


; ------------------------------------------------------------------
; MASTER ORTAMI  -> sadece src/master klasorunu derler
; ------------------------------------------------------------------
[env:master]
upload_port = COM19
monitor_port = COM19
build_src_filter = +<master/> -<slave/>

; ------------------------------------------------------------------
; SLAVE ORTAMI    -> sadece src/slave klasorunu derler
; ------------------------------------------------------------------
[env:slave]
upload_port = COM20
monitor_port = COM20
build_src_filter = +<slave/> -<master/>